Ticket 4
mikesealey/nc-news pull request #1
Opened 2023-07-17 14:34 UTC by mikesealey

2023-07-17 14:45 UTC, NRMSMITH requested changes
I've left you a few things that could do with changing, to make your code a lot more functional as this becomes a heavier repo. Also, I would suggest changing the font colour - it's a bit difficult on the eyes. Finally, make sure that your design is responsive (i.e. when I make the screen smaller, I can still see everything -> I shouldn't ever have to scroll sideways to see what's going on!) 

Please resubmit once done 😄

2023-07-17 14:45 UTC, NRMSMITH commented on src/components/Header.jsx
> +    console.log("In the header")
make sure to delete these!!

2023-07-17 14:45 UTC, NRMSMITH commented on src/App.jsx
> +      </Routes>
you haven't built these routes yet, so they shouldn't really appear on this ticket and branch!

2023-07-17 14:45 UTC, NRMSMITH commented on src/components/Home.jsx
> +        axios.get("https://nc-news-x8sg.onrender.com/api/articles", {})
this should be extracted into a utils folder - utilise axios create in there :)

2023-07-17 14:45 UTC, NRMSMITH commented on src/components/Home.jsx
> +                        <Link to={`/${article.article_id}`}>
Could this be extracted into an ArticleCard?

2023-07-18 10:00 UTC, itskatherine reviewed
Nice stuff Mike, a few minor points to look over, once you have you're good to merge 🙂

2023-07-18 10:06 UTC, merged